# Generated by Django 4.0.5 on 2022-06-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habruser',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
