# Generated by Django 4.0.5 on 2022-07-08 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificationapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
    ]
