# Generated by Django 4.0.5 on 2022-07-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
