# Generated by Django 4.0.5 on 2022-06-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='рейтинг'),
        ),
    ]
