# Generated by Django 4.0.5 on 2022-06-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0003_article_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='reject_moderation',
            field=models.BooleanField(default=False),
        ),
    ]
