# Generated by Django 4.0.5 on 2022-07-02 12:49

from django.db import migrations, models
import django_editorjs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0004_article_reject_moderation'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='dislikes',
            field=models.IntegerField(default=0, verbose_name='dislike'),
        ),
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='like'),
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=django_editorjs.fields.EditorJsField(),
        ),
    ]
