# Generated by Django 4.0.5 on 2022-07-02 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articleapp', '0005_article_dislikes_article_likes_alter_article_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(choices=[('LIKE', 'like'), ('DISLIKE', 'dislike')], default=None, max_length=7)),
                ('habruser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to=settings.AUTH_USER_MODEL)),
                ('marked_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='articleapp.article')),
            ],
        ),
    ]
