<<<<<<< HEAD
# Generated by Django 4.0.5 on 2022-07-02 16:16
=======
# Generated by Django 4.0.5 on 2022-07-09 09:39
>>>>>>> f2b2e0df17fd56a6df4c45b9332977959dedbbff

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articleapp', '0005_article_dislikes_article_likes_alter_article_body'),
=======
        ('commentapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articleapp', '0001_initial'),
>>>>>>> f2b2e0df17fd56a6df4c45b9332977959dedbbff
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(choices=[('LIKE', 'like'), ('DISLIKE', 'dislike')], default=None, max_length=7)),
                ('habruser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to=settings.AUTH_USER_MODEL)),
                ('marked_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='articleapp.article')),
            ],
        ),
<<<<<<< HEAD
=======
        migrations.CreateModel(
            name='CommentMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(choices=[('LIKE', 'like'), ('DISLIKE', 'dislike')], default=None, max_length=7)),
                ('habruser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_marks', to=settings.AUTH_USER_MODEL)),
                ('marked_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_marks', to='commentapp.comment')),
            ],
        ),
>>>>>>> f2b2e0df17fd56a6df4c45b9332977959dedbbff
    ]
