# Generated by Django 4.0.5 on 2022-07-08 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commentapp', '0002_comment_dislikes_comment_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('likeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(choices=[('LIKE', 'like'), ('DISLIKE', 'dislike')], default=None, max_length=7)),
                ('habruser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_marks', to=settings.AUTH_USER_MODEL)),
                ('marked_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_marks', to='commentapp.comment')),
            ],
        ),
    ]
